jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t front .
      - docker tag front $DOCKER_USERNAME/front
      - docker push $DOCKER_USERNAME/front
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/front npm run test
  