jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t front .
      - docker tag front $DOCKER_USER/front
      - docker push $DOCKER_USER/front
    - stage: test
      script: docker run --rm $DOCKER_USER/front npm run test
  