language: node_js
node_js:
  - "12"

addons:
  sonarcloud:
    organization: 'concerto'
    token:
      secure: $SECURE
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - docker build -t front .
      - docker tag front $DOCKER_USER/front
      - docker push $DOCKER_USER/front
    - stage: test
      script: 
        - sonar-scanner
        - docker run --rm $DOCKER_USER/front node_modules/react-scripts/bin/react-scripts.js test --watchAll=false
    